accounts/urls.py
from django.conf.urls import url, include
from accounts import views


app_name = 'accounts'

urlpatterns = [
    url(r'^profile_block/$', views.block_user, name='block_user'),
    url(r'^$', views.create_user_form, name='registration'),
    url(r'^list/$', views.search_users, name='list'),
    url(r'^profile/$', views.edit_profile, name='profile'),
    url(r'^craeateprofile$', views.crate_user_profile, name='createprofile'),
    url(r'^list/(?P<pk>\d+)/$', views.user_detail_view, name='detail'),
    url(r'^list_messages/(?P<pk>\d+)/$', views.user_detail_messages_view, name='detail_messages'),
    url(r'^viewprofile/$', views.UserProfileView.as_view(), name='viewprofile'),
    url(r'^confirm-deactivate/$', views.ConfirmDeactivate.as_view(), name='confirm-deactivate'),
    url(r'^deactivate/$', views.delete_profile, name='deactivate'),
    url(r'^accountsapi/$', views.UsersListAPI.as_view()),
    url(r'^accountsapi/(?P<pk>\d+)/$', views.UsersDetailAPI.as_view(), name='api_detail'),
    url(r'^acoountsapi/(?P<pk>\d+)/update/$', views.UserUpdateAPI.as_view(), name='api_update'),

]

friends/urls.py
from django.conf.urls import url
from friends import views

app_name = 'friends'

urlpatterns = [
    url(r'^add/(?P<pk>\d+)/to_friends_list/$', views.add_friend_to_list, name='add_friend'),
    url(r'^view/(?P<username>[-\w]+)/friends_list/$', views.UserFriends.as_view(), name='my_list_friend'),
    url(r'^remove/(?P<pk>\d+)/$', views.delete, name='friend_remove'),

]

mymessage/urls.py
from django.conf.urls import url
from mymessage import views

app_name = 'mymessage'

urlpatterns = [
    url(r'^add_message_to/(?P<pk>\d+)/$', views.make_a_message, name='add_message'),
]

noti/urls.py
from django.conf.urls import url
from noti import views
app_name = 'noti'

urlpatterns = [
    url(r'^$', views.AllNotificationsList.as_view(), name='all'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name='delete')
]

venv_twentythree/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('berenise90silvano90/', admin.site.urls),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^noti/', include('noti.urls', 'noti')),

    url(r'^group_message/', include('message_group.urls', namespace='group_message')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
    url(r'^message/', include('mymessage.urls', namespace='message')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^todo/', include('todolist.urls', namespace='todo')),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^$', views.IndexHome.as_view(), name='home'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friends/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from accounts.models import Profile


class Friend(models.Model):
    user = models.ForeignKey(User, related_name='friends', on_delete=models.CASCADE)
    friend = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('friends:my_list_friend', kwargs={'username': self.user.username})

    class Meta:
        ordering = ['friend']

friends/forms.py
from django import forms
from .models import Friend


class MakeFriendForm(forms.ModelForm):

    class Meta:
        model = Friend
        exclude = ('user', 'friend')

friends/views.py
from accounts.models import Profile
from .forms import MakeFriendForm
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView
from .models import Friend
from django.contrib.auth import get_user_model
from django.http import Http404
from django.contrib import messages
from notify.signals import notify
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
User = get_user_model()


@login_required
def add_friend_to_list(request, pk):
    friend = get_object_or_404(Profile, pk=pk)
    if request.method == 'POST':
        form = MakeFriendForm(request.POST)
        if form.is_valid():
            user_friend_list = form.save(commit=False)
            user_friend_list.friend = friend
            user_friend_list.user = request.user
            if_obj_exists = Friend.objects.filter(friend=friend, user__exact=request.user).exists()
            if if_obj_exists:
                messages.warning(request, '{} ya esta en tu lista de amigos!'.format(friend))
                return redirect('accounts:detail', pk=pk)

            else:

                notify.send(sender=request.user, actor=request.user, recipient=friend.user, verb='te agrego a la lista de amigos',
                            nf_type='followed_by_one_user')

                messages.success(request, '{} fue agregado a tus amigos!'.format(friend))
                user_friend_list.save()
                return redirect('accounts:detail', pk=pk)


class UserFriends(ListView, LoginRequiredMixin):

    context_object_name = 'friend_list'
    model = Friend
    template_name = 'friends/user_friend_list.html'

    def get_queryset(self):
        try:
            self.owner_of_friends = User.objects.prefetch_related('friends').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.owner_of_friends.friends.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['friend_user'] = self.owner_of_friends
        return context


@login_required
def delete(request, pk):
    query = Friend.objects.filter(user__exact=request.user, friend_id__exact=pk)
    query.delete()
    return redirect('friends:my_list_friend', username=request.user.username)

friends/templates/friends/user_friend_list.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block body_block %}

<div class="d-flex justify-content-center">

    <h2>Amigos</h2>
</div>
    <br>

     <div class="container">
    <div class="row">

    {% for friends in friend_list %}
     <div class="col-md-4">


                        <div class="card bg-light mb-3">
            <img class="card-img-top friends" src="{{ friends.friend.profile_pic.url }}" alt="Card image cap">
            <div class="card-body">
                <p class="card-title">{{ friends.friend }}</p>
                <div class="card-text">

                            <div class="btn-group" role="group" aria-label="Basic example">
        <a href="{% url 'message:add_message' pk=friends.friend.id %}" class="btn btn-outline-primary">Enviar Mensaje</a>
        <a href="{% url 'accounts:detail_messages' pk=friends.friend.id %}" class="btn btn-outline-warning">Ver Mensajes</a>
        </div>
                </div>
                           <br>
     <p class="card-text"><a href="{% url 'friends:friend_remove' pk=friends.friend.id %}" class="btn btn-outline-danger">Remover</a></p>


            </div>

        </div>
                    </div>
        {% if forloop.counter|divisibleby:"3" and not forloop.last %}
            </div><div class="row">
        {% endif %}
    {% endfor %}
        </div>
    </div>

{#        {% if friends.friend.profile_pic %}#}
{##}
{#        <img src="{{ friends.friend.profile_pic.url }}" width="240px">#}
{#    {% endif %}#}
{##}
{#        <p>{{ friends.friend }}</p>#}
{#        <div class="btn-group" role="group" aria-label="Basic example">#}
{#        <a href="{% url 'message:add_message' pk=friends.friend.id %}" class="btn btn-light">Message {{ friends.friend }}</a>#}
{#        <a href="{% url 'accounts:detail_messages' pk=friends.friend.id %}" class="btn btn-light">View Messages</a>#}
{#        <a href="{% url 'friends:friend_remove' pk=friends.friend.id %}" class="btn btn-light">Remove {{ friends.friend }}</a>#}
{#        </div>#}
{##}
{#        <br>#}
        <br>





{% endblock %}